import React from 'react';
import ServiceTypeTable from './Component/ServiceTypeTable';

export const metadata = {
  title: 'Service',
  description: 'Generated by create next app',
};

export default function page() {
  return (
    <div className="w-full">
      <ServiceTypeTable />
    </div>
  );
}
