import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/Component/Shared/Navber';
import ResponsiveContainer from '@/Component/ResponsiveContainer/ResponsiveContainer';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import { mainTheme } from '@/theme/mainTheme';
import NextJsTopLoader from '@/Component/Shared/NextTopLoader/NextTopLoader';
import { Footer } from '@/Component/Shared/Footer/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextJsTopLoader />
        <Navbar />
        <AntdRegistry>
          <ConfigProvider theme={mainTheme}>
            <ResponsiveContainer className={'md:!mt-[115px] !mt-20'}>
              <div className="w-full">
                <h1 className="text-3xl font-bold  text-center uppercase !my-5">Velkii Agent</h1>
                <div className="overflow-hidden whitespace-nowrap border-y border-gray-300 py-2 bg-white">
                  <div className=" cursor-pointer text-lg font-bold text-center uppercase text-red-600 !py-2">
                    হোয়াটসঅ্যাপ ব্যতীত অন্য কোনো অ্যাপের মাধ্যমে যোগাযোগ বা লেনদেন করা যাবে না, এবং
                    করলে তা গ্রহণযোগ্য হবে না
                  </div>
                </div>
                {children}
              </div>
            </ResponsiveContainer>
          </ConfigProvider>
        </AntdRegistry>

        <Footer />
      </body>
    </html>
  );
}
