import React from 'react';
import AdminTypetable from './Component/AdminTypetable';

export const metadata = {
  title: 'Admin',
  description: 'Generated by create next app',
};

export default function page() {
  return (
    <div className="w-full">
      <AdminTypetable />
    </div>
  );
}
