import React from 'react';
import MasterTypetable from './Component/MasterTypetable';

export const metadata = {
  title: 'Master',
  description: 'Generated by create next app',
};

export default function page() {
  return (
    <div className="w-full">
      <MasterTypetable />
    </div>
  );
}
