import React from 'react';
import AntDForm from './_Component/DataUploadForm';

export const metadata = {
  title: 'Data Upload',
  description: 'Generated by create next app',
};

const page = () => {
  return (
    <div>
      <AntDForm />
    </div>
  );
};

export default page;
